import { useState } from "react";
import { TextPane } from "./components/TextPane";
import { ResultsPanel } from "./components/ResultsPanel";
import { ExamplePicker } from "./components/ExamplePicker";
import { analyzeTextPair } from "./analysis/analyzeTextPair";
import type { AnalysisResult } from "./analysis/types";
import { goldenExamples } from "./examples/goldenExamples";

const initialExample = goldenExamples[0];

function App() {
  const [selectedExampleId, setSelectedExampleId] = useState(initialExample.id);
  const [versionA, setVersionA] = useState(initialExample.versionA);
  const [versionB, setVersionB] = useState(initialExample.versionB);
  const [result, setResult] = useState<AnalysisResult | null>(
    analyzeTextPair(initialExample.versionA, initialExample.versionB),
  );

  const selectedExample =
    goldenExamples.find((example) => example.id === selectedExampleId) ?? initialExample;

  const handleCompare = () => {
    setResult(analyzeTextPair(versionA, versionB));
  };

  const handleLoadExample = () => {
    setVersionA(selectedExample.versionA);
    setVersionB(selectedExample.versionB);
    setResult(analyzeTextPair(selectedExample.versionA, selectedExample.versionB));
  };

  const handleReset = () => {
    setVersionA("");
    setVersionB("");
    setResult(null);
  };

  return (
    <div className="app-shell">
      <header className="hero">
        <div>
          <p className="eyebrow">SameDiff</p>
          <h1>SameDiff Lens</h1>
          <p className="hero-copy">
            Compare two text versions and surface likely semantic drift that raw line diff
            misses.
          </p>
        </div>
        <div className="badge-row">
          <span className="badge">Local-only</span>
          <span className="badge">Browser-run</span>
          <span className="badge badge-warning">Heuristic / experimental</span>
        </div>
      </header>

      <section className="banner">
        <strong>What this v0 looks for:</strong> added concepts, removed concepts, renamed
        ideas, changed commitments, action-item drift, and possible contradictions. Results are
        generated by deterministic heuristics, not an LLM.
      </section>

      <section className="controls-panel">
        <ExamplePicker
          examples={goldenExamples}
          selectedExampleId={selectedExampleId}
          onSelectedExampleIdChange={setSelectedExampleId}
          onLoadExample={handleLoadExample}
        />
        <div className="button-row">
          <button className="button button-primary" type="button" onClick={handleCompare}>
            Compare
          </button>
          <button className="button" type="button" onClick={handleReset}>
            Reset
          </button>
        </div>
      </section>

      <section className="example-note">
        <div>
          <h2>{selectedExample.title}</h2>
          <p>{selectedExample.description}</p>
        </div>
        <div className="expectation-block">
          <span className="mini-label">Expected spirit</span>
          <ul>
            {selectedExample.expectedSignals.map((signal) => (
              <li key={signal}>{signal}</li>
            ))}
          </ul>
        </div>
      </section>

      <main className="workspace">
        <div className="pane-grid">
          <TextPane
            label="Version A"
            value={versionA}
            onChange={setVersionA}
            placeholder="Paste the baseline text here."
          />
          <TextPane
            label="Version B"
            value={versionB}
            onChange={setVersionB}
            placeholder="Paste the revised text here."
          />
        </div>

        <ResultsPanel result={result} hasInput={Boolean(versionA.trim() || versionB.trim())} />
      </main>

      <footer className="app-footer">
        <span>SameDiff Lens is heuristic / experimental.</span>
        <a
          href="https://github.com/henry-filgueiras/samediff-lens"
          target="_blank"
          rel="noreferrer"
        >
          View source on GitHub
        </a>
      </footer>
    </div>
  );
}

export default App;
